version: 2

# Specify Python version and build system
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Install your package and docs requirements
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# This is the REQUIRED key mentioned in the error
sphinx:
  configuration: docs/conf.py
